# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '*/1 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: commit and push
        run: |
            git init
            git config --global user.name 'anhpnv'
            git config --global user.email 'nhuvietanh271098@gmail.com'
            git remote add origin https://github.com/${{ github.repository }}
            git config --global push.default current
            git remote set-url origin https://${{ secrets.PASS_TOKEN }}@github.com/${{ github.repository }}
            git commit --allow-empty -m "Test allow empty commit"
            git push --force
