# This is a basic workflow to help you get started with Actions

name: Trigger Site Rebuild on a CRON Schedule

# Controls when the workflow will run
on:
  schedule:
  - cron: "*/2 * * * *"
    # - cron: "*/1 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: commit and push
        run: |
            git init
            git config --global user.name 'anhpnv'
            git config --global user.email 'nhuvietanh271098@gmail.com'
            git remote add origin https://github.com/${{ github.repository }}
            git config --global push.default current
            git remote set-url origin https://${{ secrets.PASS_TOKEN }}@github.com/${{ github.repository }}
            git commit --allow-empty -m "Update Star"
            git push --force
